#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

MODIFIED_FILES=$(git diff-index --cached --name-only HEAD)

if ! COMMIT_TEMPLATE=$(echo "$MODIFIED_FILES" | cargo run -- commit-template) ; then
  >&2 echo "Please follow mkchlog rules"
  exit 1
fi

echo "$(echo "$COMMIT_TEMPLATE" | cat - "$COMMIT_MSG_FILE")" > "$COMMIT_MSG_FILE"
