skip-merge-commits: true

sections:
    # section identifier selected by project maintainer
    security:
        # The header presented to the user
        title: Security
        # desctiption is optional and will appear above changes
        description: This section contains very important security-related changes.
        subsections:
            vuln_fixes:
                title: Fixed vulnerabilities
    features:
        title: New features
    bug_fixes:
        title: Fixed bugs
    breaking:
        title: Breaking changes
    perf:
        title: Performance improvements
    dev:
        title: Development
        description: Internal development changes
