name: Test

on:
  push:
    branches: [ master, ci ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mkchlog
        uses: actions/checkout@v2
      - name: Checkout toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Test mkchlog
        run: cargo test
      - name: Checkout MSRV toolchain
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@1.63.0
      - name: Test mkchlog on MSRV
        run: cargo +1.63.0 test
      - name: Check wasm bindings
        run: cargo +1.63.0 check --manifest-path wasm/Cargo.toml
